csvDir <- "../resources/";
rapportDir <- "../../Rapport/";

# Récupération du nom des fichiers csv dans le répertoire "resources"
csvFiles <- list.files(path=csvDir, pattern="*.csv")

fullPathCsvFiles <- c()
for(csvFile in csvFiles) {
  file <- paste(csvDir, csvFile, sep="", collapse=NULL)
  fullPathCsvFiles <- c(fullPathCsvFiles, file)
}

# lecture des fichiers
print(paste("Lecture ", fullPathCsvFiles[1]))
data1 <- read.csv(file=fullPathCsvFiles[1], header=TRUE, sep=";")
print(paste("Lecture ", fullPathCsvFiles[2]))
data2 <- read.csv(file=fullPathCsvFiles[2], header=TRUE, sep=";")
print(paste("Lecture ", fullPathCsvFiles[3]))
data3 <- read.csv(file=fullPathCsvFiles[3], header=TRUE, sep=";")

print("Plot y = BestEyeCurveRadius(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_curve_radius.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.curve.radius, type="l", xlab="generation", ylab="best eye curve radius", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.curve.radius, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.curve.radius, type="l", col="green", lwd=2.5)
legend(40000, 10000, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeCurveRadius(Generation)")
dev.off()

print("Plot y = BestEyeIrisSize(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_iris_size.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.iris.size, type="l", xlab="generation", ylab="best eye iris size", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.iris.size, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.iris.size, type="l", col="green", lwd=2.5)
legend(40000, 0.5, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeIrisSize(Generation)")
dev.off()

print("Plot y = BestEyeAngle(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_angle.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.angle, type="l", xlab="generation", ylab="best eye angle", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.angle, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.angle, type="l", col="green", lwd=2.5)
legend(0, 0.14, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeAngle(Generation)")
dev.off()

print("Plot y = BestEyeRefractionIndex(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_refraction_index.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.refraction.index, type="l", xlab="generation", ylab="best eye angle", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.refraction.index, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.refraction.index, type="l", col="green", lwd=2.5)
legend(0, 1.44, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeRefractionIndex(Generation)")
dev.off()

print("Plot y = BestEyeDepth(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_depth.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.depth, type="l", xlab="generation", ylab="best eye depth", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.depth, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.depth, type="l", col="green", lwd=2.5)
legend(0, 0.8, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeDepth(Generation)")
dev.off()

print("Plot y = BestEyeAperture(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_aperture.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.aperture, type="l", xlab="generation", ylab="best eye aperture", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.aperture, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.aperture, type="l", col="green", lwd=2.5)
legend(40000, 1.4, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeAperture(Generation)")
dev.off()

print("Plot y = BestEyeRatio(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_ratio.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.ratio, type="l", xlab="generation", ylab="best eye ratio", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.ratio, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.ratio, type="l", col="green", lwd=2.5)
legend(40000, 900, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeRatio(Generation)")
dev.off()

print("Plot y = BestEyeSightAngle(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_sight_angle.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.sight.angle, type="l", xlab="generation", ylab="best eye sight angle", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.sight.angle, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.sight.angle, type="l", col="green", lwd=2.5)
legend(40000, 3.0, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeSightAngle(Generation)")
dev.off()

print("Plot y = BestEyeFitness(Generation) ")
jpeg(file=paste(rapportDir, "best_eye_fitness.jpeg", sep="", collapse=NULL))
plot(data1$generation, data1$best.eye.fitness, type="l", xlab="generation", ylab="best eye fitness", col="blue", lwd=2.5)
lines(data2$generation, data2$best.eye.fitness, type="l", col="red", lwd=2.5)
lines(data3$generation, data3$best.eye.fitness, type="l", col="green", lwd=2.5)
legend(0, 70000, legend=c("Data1", "Data2", "Data3"), col=c("blue", "red", "green"), lty=1, cex=0.8)
title(main="BestEyeFitness(Generation)")
dev.off()